services:

  # APISIX
  apisix:
    image: apache/apisix:3.13.0-debian
    container_name: nemobil-apisix
    restart: unless-stopped

    networks:
      - nemobil

    ports:
      - "8080:9080"

    volumes:
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml



  # Keycloak and its PostgreSQL DB
  keycloak:
    # image: quay.io/keycloak/keycloak:26.5
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: nemobil-keycloak
    restart: unless-stopped
    networks:
      - nemobil

    command:
      - start-dev
      - --import-realm

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # 26.5 KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      # 26.5 KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_DEBUG: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: "true"

    volumes:
      - ../config/keycloak:/opt/keycloak/data/import

    # Healthcheck 26.5
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "exec 3<>/dev/tcp/127.0.0.1/9000 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q UP"
    #     ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 15


    # Healthcheck 21.1.1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /realms/master HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q 'master'"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
  
    depends_on:
      keycloak-postgres:
        condition: service_healthy

  keycloak-postgres:
    image: postgres:16.9
    container_name: nemobil-keycloak-postgres
    restart: unless-stopped
    networks:
      - nemobil

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${KEYCLOAK_DB_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10



  # Stellio with its Kafka, PostgreSQL DB, API Gateway, Search and Subscription Services
  kafka:
    image: apache/kafka:3.9.0
    container_name: nemobil-kafka
    restart: unless-stopped
    networks:
      - nemobil

    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

    volumes:
      - kafka-data:/var/lib/kafka/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  stellio-postgres:
    image: stellio/stellio-timescale-postgis:16-2.26.4-3.6
    container_name: nemobil-stellio-postgres
    restart: unless-stopped
    networks:
      - nemobil

    environment:
      POSTGRES_DBNAME: ${STELLIO_SEARCH_DB_DATABASE},${STELLIO_SUBSCRIPTION_DB_DATABASE}
      POSTGRES_USER: ${STELLIO_DB_USER}
      POSTGRES_PASS: ${STELLIO_DB_PASSWORD}
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,timescaledb,pgcrypto
      ACCEPT_TIMESCALE_TUNING: "TRUE"

    volumes:
      - stellio-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${STELLIO_DB_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    image: stellio/stellio-api-gateway:${STELLIO_DOCKER_TAG}
    container_name: nemobil-stellio-api-gateway
    restart: unless-stopped
    networks:
      - nemobil

    environment:
      - SPRING_PROFILES_ACTIVE=${ENVIRONMENT}
      - APPLICATION_SEARCH_SERVICE_URL=http://search-service:8083
      - APPLICATION_SUBSCRIPTION_SERVICE_URL=http://subscription-service:8084
      
  search-service:
    image: stellio/stellio-search-service:${STELLIO_DOCKER_TAG}
    container_name: "${CONTAINER_NAME_PREFIX}stellio-search-service"
    restart: unless-stopped
    networks:
      - nemobil

    environment:
      - SPRING_PROFILES_ACTIVE=${ENVIRONMENT}
      - SPRING_R2DBC_URL=r2dbc:pool:postgresql://stellio-postgres/${STELLIO_SEARCH_DB_DATABASE}
      - SPRING_FLYWAY_URL=jdbc:postgresql://stellio-postgres/${STELLIO_SEARCH_DB_DATABASE}
      - SPRING_R2DBC_USERNAME=${STELLIO_DB_USER}
      - SPRING_R2DBC_PASSWORD=${STELLIO_DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APPLICATION_AUTHENTICATION_ENABLED=${STELLIO_AUTHENTICATION_ENABLED}
      - STELLIO_AUTHENTICATION_ALLOW_PUBLIC_PERMISSION=${STELLIO_AUTHENTICATION_ALLOW_PUBLIC_PERMISSION}
      - APPLICATION_TENANTS_0_ISSUER=${APPLICATION_TENANTS_0_ISSUER}
      - APPLICATION_TENANTS_0_NAME=${APPLICATION_TENANTS_0_NAME}
      - APPLICATION_TENANTS_0_DBSCHEMA=${APPLICATION_TENANTS_0_DBSCHEMA}
      - APPLICATION_PAGINATION_LIMIT-DEFAULT=${APPLICATION_PAGINATION_LIMIT_DEFAULT}
      - APPLICATION_PAGINATION_LIMIT-MAX=${APPLICATION_PAGINATION_LIMIT_MAX}
      - APPLICATION_PAGINATION_TEMPORAL-LIMIT=${APPLICATION_PAGINATION_TEMPORAL_LIMIT}

    depends_on:
      stellio-postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  subscription-service:
    container_name: "${CONTAINER_NAME_PREFIX}stellio-subscription-service"
    image: stellio/stellio-subscription-service:${STELLIO_DOCKER_TAG}
    restart: unless-stopped
    networks:
      - nemobil

    environment:
      - SPRING_PROFILES_ACTIVE=${ENVIRONMENT}
      - SPRING_R2DBC_URL=r2dbc:pool:postgresql://stellio-postgres/${STELLIO_SUBSCRIPTION_DB_DATABASE}
      - SPRING_FLYWAY_URL=jdbc:postgresql://stellio-postgres/${STELLIO_SUBSCRIPTION_DB_DATABASE}
      - SPRING_R2DBC_USERNAME=${STELLIO_DB_USER}
      - SPRING_R2DBC_PASSWORD=${STELLIO_DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - APPLICATION_AUTHENTICATION_ENABLED=${STELLIO_AUTHENTICATION_ENABLED}
      - STELLIO_AUTHENTICATION_ALLOW_PUBLIC_PERMISSION=${STELLIO_AUTHENTICATION_ALLOW_PUBLIC_PERMISSION}
      - APPLICATION_TENANTS_0_ISSUER=${APPLICATION_TENANTS_0_ISSUER}
      - APPLICATION_TENANTS_0_NAME=${APPLICATION_TENANTS_0_NAME}
      - APPLICATION_TENANTS_0_DBSCHEMA=${APPLICATION_TENANTS_0_DBSCHEMA}
      - APPLICATION_TENANTS_0_CLIENTID=${APPLICATION_TENANTS_0_CLIENTID}
      - APPLICATION_TENANTS_0_CLIENTSECRET=${APPLICATION_TENANTS_0_CLIENTSECRET}
      - SUBSCRIPTION_ENTITY-SERVICE-URL=${SUBSCRIPTION_ENTITY_SERVICE_URL}
      - SUBSCRIPTION_STELLIO_URL=${SUBSCRIPTION_STELLIO_URL}
      - APPLICATION_PAGINATION_LIMIT-DEFAULT=${APPLICATION_PAGINATION_LIMIT_DEFAULT}
      - APPLICATION_PAGINATION_LIMIT-MAX=${APPLICATION_PAGINATION_LIMIT_MAX}
    
    depends_on:
      stellio-postgres:
        condition: service_healthy
      kafka:
        condition: service_started



  # NodeRed
  nodered:
    image: nodered/node-red:4.1
    container_name: nemobil-nodered
    restart: unless-stopped

    networks:
      - nemobil

    environment:
      MQTT_USER: ${MQTT_NODERED_USER}
      MQTT_PASSWORD: ${MQTT_NODERED_PASSWORD}
    
    volumes:
      - nodered-data:/data

    depends_on:
      kafka:
        condition: service_healthy



  # Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    container_name: nemobil-mosquitto
    restart: unless-stopped

    networks:
      - nemobil

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    ports:
      - "1883:1883"




  # Mobile App Backend
  nemobil-core-api:
    image: boostfiware/nemobil-coreapi:1.1.1
    container_name: nemobil-core-api
    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      # Web server
      HTTP_PORT: ${HTTP_PORT}
      GLOBAL_PREFIX: ${GLOBAL_PREFIX}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}

      # POIs
      POIS_ENABLED: ${POIS_ENABLED}
      POIS_ADMIN_PASSWORD: ${POIS_ADMIN_PASSWORD}
      POIS_FILE_PATH: ${POIS_FILE_PATH}

      # Frontend
      CORS: ${CORS}
      REDIRECT_URL: ${KEYCLOAK_REDIRECT_ENDPOINT}

      # Keycloak
      TOKEN_ENDPOINT: ${KEYCLOAK_INTERNAL_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
      REGISTER_ENDPOINT: ${KEYCLOAK_PUBLIC_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/registrations
      JWKS_URL: ${KEYCLOAK_INTERNAL_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

      CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

      SERVICE_ACCOUNT_USER: ${KEYCLOAK_SERVICE_ACCOUNT_USER}
      SERVICE_ACCOUNT_PASSWORD: ${KEYCLOAK_SERVICE_ACCOUNT_PASSWORD}

      # Stellio
      CONTEXT_API_URL: ${STELLIO_CONTEXT_API_URL}
      NGSI_JSON_LD_CONTEXT: ${NEMOBIL_NGSI_JSON_LD_CONTEXT}

      # Geocoding
      LOCATIONIQ_API_KEY: ${LOCATIONIQ_API_KEY}
      LOCATIONIQ_URL: ${LOCATIONIQ_URL}

      NOMINATIM_URL: ${NOMINATIM_URL}
      NOMINATIM_USER_AGENT: ${NOMINATIM_USER_AGENT}
      NOMINATIM_COUNTRY_CODES: ${NOMINATIM_COUNTRY_CODES}
      NOMINATIM_LIMIT: ${NOMINATIM_LIMIT}

    networks:
      - nemobil

    volumes:
      - pois-data:/data

    depends_on:
      keycloak:
        condition: service_healthy
      api-gateway:
        condition: service_started

  # Mobile App Backend
  nemobil-pwa:
    image: boostfiware/nemobil-pwa:1.1.0
    container_name: nemobil-pwa
    restart: unless-stopped

    networks:
      - nemobil
      
    environment:
      BACKEND_URL: ${BACKEND_URL}
      CORE_API_URL: ${CORE_API_URL}

      DISABLE_REGISTRATION: ${DISABLE_REGISTRATION}
      DISABLE_WITH_PASSENGERS: ${DISABLE_WITH_PASSENGERS}

      GEOJSON_PATH: ${GEOJSON_PATH}

      MAP_TILE_URL: ${MAP_TILE_URL}
      MAP_TILE_ATTRIBUTION: ${MAP_TILE_ATTRIBUTION}

      DATAPOLICY_PDF_DE: ${DATAPOLICY_PDF_DE}
      DATAPOLICY_PDF_EN: ${DATAPOLICY_PDF_EN}

    volumes:
      - ./nemobil-pwa-privacydocs:/usr/share/nginx/html/datenschutz:ro

    depends_on:
      - nemobil-core-api

volumes:
  keycloak-postgres-data:
  kafka-data:
  stellio-postgres-data:
  nodered-data:
  pois-data:



networks:
  nemobil:
    name: nemobil